### ISSUE TITLE
Inventory.AddItem can add items with a quantity of 0

### ISSUE THREAD

**Issue by ipdae** [planetarium/lib9c#1080]
## Context

This bug was found in https://github.com/planetarium/lib9c/pull/1073. [`Inventory`](https://github.com/planetarium/lib9c/blob/e976cfeabbe41cc64877ac4e2d5f18797960bf20/Lib9c/Model/Item/Inventory.cs) class has to prevent to add item with 0 quantity.

## Tips

- You can see the logic to add items at [`Inventory.AddItem`](https://github.com/planetarium/lib9c/blob/e976cfeabbe41cc64877ac4e2d5f18797960bf20/Lib9c/Model/Item/Inventory.cs#L176-L193)
   https://github.com/planetarium/lib9c/blob/e976cfeabbe41cc64877ac4e2d5f18797960bf20/Lib9c/Model/Item/Inventory.cs#L176-L193
- Check its `count` argument and throw [`ArgumentOutOfRangeException`](https://learn.microsoft.com/en-us/dotnet/api/system.argumentoutofrangeexception?view=net-8.0)

**Comment by HwiYul-G** [comment]
댓글 달았습니다!
