### ISSUE TITLE
Reference Libplanet as ProjectReference w/ submodules instead of PackageReference

### ISSUE THREAD

**Issue by dahlia** [planetarium/lib9c#110]
Some kind of bugs require to modify both Libplanet and Lib9c.  On such situations, `PackageReference` requires Libplanet to be changed first and *released* to NuGet, which makes iteration latency longer.

Hence, for the sake of easier debugging, I suggest to reference Libplanet as `ProjectReference` with Git submodules instead of `PackageReference`.

**Comment by moreal** [comment]
Lib9c references Libplanet as `ProjectReference` now.
