### ISSUE TITLE
`InvalidBlockStateRootHashException` on #4286622

### ISSUE THREAD

**Issue by area363** [planetarium/lib9c#1265]
https://9cscan.com/blocks/4286622
Actions: 
* Stake
* RankingBattle12
* DailyRewards6
* UpdateSell2

```
Libplanet.Blocks.InvalidBlockStateRootHashException: Block #4286622
52458c06be056d5c8cda5361eae62bb5182a03ed175e6e8dc356de0e54cb6c00's state root hash is
5e287b1a9302ca2e23afbe956e7e6e980aab8c1c37809bdbc124c9f8b23e109e, but the execution result is
f291fa791aa9ca759490ed6be9fb2b63a09ded2a596cadbcdf8897efaa24c15d.
```

**Comment by longfin** [comment]
`5e287b1a9302ca2e23afbe956e7e6e980aab8c1c37809bdbc124c9f8b23e109e`: A state root hash when `stake` failed.
`f291fa791aa9ca759490ed6be9fb2b63a09ded2a596cadbcdf8897efaa24c15d`: A state root hash when `stake` succeed.

**Comment by longfin** [comment]
could you check it? @moreal

**Comment by area363** [comment]
<9c-main-full-state txResult query>
```
query{
  transaction{
    transactionResult(txId: "e183c1c3eb8319ff50ec13f9a53b51ff3a479e8a946e475ca0a46bbb73cd7f44"){
      txStatus
      exceptionName
    }
  }
}

{
  "data": {
    "transaction": {
      "transactionResult": {
        "txStatus": "FAILURE",
        "exceptionName": "Nekoyume.Action.FailedLoadStateException"
      }
    }
  },
  "extensions": {}
}
```

However, the current version(v100260) doesn't return an error and goes through https://github.com/planetarium/lib9c/blob/v100260/Lib9c/Action/Stake.cs#L91. I'll write more when I know more 🙏

**Comment by area363** [comment]
The same situation described above occurs for https://9cscan.com/blocks/4286627.

I've been able to append those blocks by adding a condition like below:
```
if (context.BlockIndex > 4286622 && context.BlockIndex < 4286628)
{
       return states;
}
```

I'll check how far this case continues in our chain @moreal

**Comment by area363** [comment]
https://github.com/planetarium/lib9c/issues/1265

& currently working on fixing the original action.

**Comment by area363** [comment]
This issue has been resolved by https://github.com/planetarium/lib9c/issues/1265 with the updated `Stake0` action.
