### ISSUE TITLE
Update C# language version

### ISSUE THREAD

**Issue by U-lis** [planetarium/lib9c#1295]
Lib9c is currently using dotnet 8.0 as C# version.
I think we can update C# language version (9, maybe 10?) to use latest features

### Remark
- lib9c `MUST` guarantee to meet netstandard 2.0. Check possible issues due to update C# version

Related Issue : #1292 ([Comment thread](https://github.com/planetarium/lib9c/pull/1292#discussion_r944164417))

**Comment by moreal** [comment]
When this issue was opened, the C# version was 8 and it is 9 now. C# 9 is the latest version that latest Unity version supports. So this issue can be closed as resolved, and cannot use more latest C# versions until Unity supports them or Lib9c drops support for Unity.
