### ISSUE TITLE
`EquipmentExtensions.IsMadeWithMimisbrunnrRecipe()` not work

### ISSUE THREAD

**Issue by sonohoshi** [planetarium/lib9c#1317]
If optionRows(of MimisBrunnr) has temporary value, This method not works.
All of equipments would make by MimisBrunnr recipe.

case:
```cs
Equipment has option(ATK, 80)
🔽Checking IsMadeWithMimisbrunnrRecipe...

mimisRecipeOption.StatMin = 1 (temporary value)
return option.value >= mimisRecipeOption.StatMin; (it always true)
```
Therefore, all the equipment is mistaken as if it were made by recipe of mimis brunnr.

**Comment by U-lis** [comment]
Mimisbrunnr is gone :sob:
