### ISSUE TITLE
Ambiguity of CheckObsolete() and CheckActionAvailable() method

### ISSUE THREAD

**Issue by boscohyun** [planetarium/lib9c#1507]
There are some methods for manage the actions lifecycle.

- [ActionBase.CheckObsolete()](https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/ActionBase.cs#L425-L431)
- [ActionBase.CheckActionAvailable()](https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/ActionBase.cs#L438-L444)

These methods are little bit ambiguity.

## ActionBase.CheckObsolete()

```cs
protected void CheckObsolete(long obsoleteIndex, IActionContext ctx)
{
    if (ctx.BlockIndex > obsoleteIndex)
    {
        throw new ActionObsoletedException();
    }
}
```

I expect to occur an exception when `obsoleteIndex` is smaller than or equal to `ctx.BlockIndex`. Because the name of `obsoleteIndex` looks so. Below is my suggestion and if it will applied, all of values used to `obsoleteIndex` will `+1`.

- Check `obsoleteIndex` is smaller than or equal to `ctx.BlockIndex`
- `+1` all of values used to `obsoleteIndex`

```cs
protected void CheckObsolete(long obsoleteIndex, IActionContext ctx)
{
    if (obsoleteIndex <= ctx.BlockIndex)
    {
        throw new ActionObsoletedException();
    }
}
```

## ActionBase.CheckActionAvailable()

```cs
protected void CheckActionAvailable(long startedIndex, IActionContext ctx)
{
    if (ctx.BlockIndex <= startedIndex)
    {
        throw new ActionUnavailableException();
    }
}
```

Below is my suggestion.

- Change `startedIndex` to `availableIndex`
- Check `availableIndex` is greater than `ctx.BlockIndex`
- `-1` all of values used to `availableIndex`

```cs
protected void CheckActionAvailable(long availableIndex, IActionContext ctx)
{
    if (availableIndex > ctx.BlockIndex)
    {
        throw new ActionUnavailableException();
    }
}
```

**Comment by U-lis** [comment]
Since PAEV arrived, we don't need to consider action obsoletion :tada:
