### ISSUE TITLE
Overflow in action

### ISSUE THREAD

**Issue by boscohyun** [planetarium/lib9c#1608]
The lib9c has several overflowable lines. It is not problem now but it should be managed.
Below is only part of the whole.

- https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/CombinationEquipment.cs#L401-L402
- https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/CombinationEquipment.cs#L594
- https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/CombinationEquipment.cs#L604
- https://github.com/planetarium/lib9c/blob/main/Lib9c/Action/CombinationEquipment.cs#L644

**Comment by U-lis** [comment]
The codebase has been changed too much, so this issue does not point which one is target.
I think it's better to close this issue and refine the action someday :wink:
