### ISSUE TITLE
[신규 스킬] TwinAttack 의 데미지가 예상과 다르게 적용되는 현상

### ISSUE THREAD

**Issue by U-lis** [planetarium/lib9c#2471]
TwinAttack 스킬이 발동되었을 때 기대하는 데미지는 Combo 의 영향에 따라 100% > 200% 의 증가 데미지이다.
하지만 실제로 TwinAttack 에서 보이는 데미지는 1타를 100% 로 했을 때 100% > 400% 정도로 큰 증가가 있다.
```
무기 데미지 : 53391
보스 DEF : 2080

- 1타 : 47150
- 2타 : 197019
----
무기 데미지 : 60104
보스 DEF : 2080

- 1타 : 67366
- 2타 : 281074
```

**Comment by U-lis** [comment]
### Damage 계산의 구조
1. 공격자의 Stat 을 기반으로 데미지를 계산한다.
2. 2타 이상의 공격을 하는 경우 일정 비율에 따라 이 데미지를 나눠서 여러번에 걸쳐 주도록 한다.
    1. 2타의 경우 0.35 / 0.65 로 데미지가 나뉘어 들어간다.
3. 이후 combo 적용을 해야 하는 경우 combo 수에 따른 배수 처리를 해 최종 데미지를 계산한다.

### TwinAttack 계산 과정
1. 공격자가 100의 데미지로 공격한다.
2. 1타는 35로 축소되고, combo 배수 1을 받아서 35의 데미지가 들어간다.
3. 2타는 65로 축소되고, combo 배수 2를 받아서 130의 데미지가 들어간다.
4. 총 데미지만 봐서는 예상 300 > 165로 오히려 감소했으나, 보기에는 1타 대비 2타가 4배정도 센 것처럼 보인다.

**Comment by sonohoshi** [comment]
@U-lis 이거 혹시 무기 데미지와는 별개로 옵션에 붙어있는 DoubleAttack의 Power가 몇으로 박혀있나요? 그걸 확인해봐야 정확한 계산이 될 것 같아서요

**Comment by U-lis** [comment]
제가 테스트한건 unit test 에 skill power 100 으로 강제로 넣고 돌린거라 power 가 100 일겁니다.
[이 테스트케이스](https://github.com/planetarium/lib9c/blob/b3ef852d87ff90597ce1aeefcdb41fd78f8a82f8/.Lib9c.Tests/Model/Skill/Adventure/DoubleAttackTest.cs#L30) 로 테스트했습니다.

> @U-lis 이거 혹시 무기 데미지와는 별개로 옵션에 붙어있는 DoubleAttack의 Power가 몇으로 박혀있나요? 그걸 확인해봐야 정확한 계산이 될 것 같아서요

**Comment by sonohoshi** [comment]
아까부터 계속 보고있는데 이해한 코드랑 나와야하는 값이 이해가 잘 안돼서 좀 보고있었습니다 👌 감사합니다

**Comment by U-lis** [comment]
연출과 별도로 최종 데미지 합은 기대한 것과 비슷해서 일단 현재 방식을 기준으로 수치를 잡아보고 수정이 필요한 경우 빠르게 수정하기로 했습니다. cc. @NineSyu

**Comment by U-lis** [comment]
확인 결과 TwinAttack 은 현재 로직을 바탕으로 수치 밸런싱을 하는 데 무리가 없어 현행대로 진행하기로 결정했습니다.
