### ISSUE TITLE
The `CombinationEquipmentTest.Execute()` test is often broken.

### ISSUE THREAD

**Issue by boscohyun** [planetarium/lib9c#262]
# Problem
The reason is that the `Equipment.GetOptionCount()` function behaves differently than expected.
It seems to return the number of options, but it actually returns the sum of the number of additional stats, skills, and buff skills.
In a situation where two options are assigned to equipment, `Equipment.GetOptionCount()` returns 1 if both options are for the same stat.

# Correction direction.
1. Modify the name of `Equpment.GetOptionCount()` to suit the function.
2. In `CombinationEquipmentText.Execute()`, instead of `Equipment.GetOptionCount()`, the number of options is checked in another way.

**Comment by ipdae** [comment]
In my opinion, this will be solved by fixed random seed in unit test.
