### ISSUE TITLE
Add Unlock Combination Slot Action

### ISSUE THREAD

**Issue by U-lis** [planetarium/lib9c#2706]
Create new 4 craft slots
Unlock craft slot by purchasing

**Comment by eugene-doobu** [comment]
참고: EventConsumableItemCrafts
이유: 쌔삥임

**Comment by eugene-doobu** [comment]
ActionManager
ActionRenderHandler -> prepare / render

**Comment by eugene-doobu** [comment]
headless -> 없던 액션이 있으면 업데이트를 못한다. graphQL query, dataprovider? 맞춰줄 수 있는거

**Comment by eugene-doobu** [comment]
UnlockBlockIndex -> 기존 장비 완성 블록인덱스를 기록하던 필드. Unlock이 다른 개념으로 사용되면서 네이밍 애매해짐

**Comment by eugene-doobu** [comment]
https://github.com/planetarium/NineChronicles.Headless/pull/2448/files#diff-b1c88aa3351a709a09254fce18e0cb40814333dbbb8b9e82cbbaf22cebc16320
