### ISSUE TITLE
Cleanup unused methods and fields in `ActionBase`

### ISSUE THREAD

**Issue by moreal** [planetarium/lib9c#2827]
There are some unused methods and fields in the `ActionBase` class. We want to make the `ActionBase` class clean without unused items. The following items should be removed:

Fields
 - `Currency ActionBase.GoldCurrencyMock`

Methods
 - `IWorld ActionBase.LogError(IActionContext context, string message, params object[] values)`
 - `void ActionBase.CheckActionAvailable(long startedIndex, IActionContext ctx)`
 - `bool ActionBase.UseV100291Sheets(long blockIndex)`

**Comment by umar-source** [comment]
Removing these unused items will help streamline the code and improve its readability. Could you please assign this task to me?

**Comment by Atralupus** [comment]
> Removing these unused items will help streamline the code and improve its readability. Could you please assign this task to me?

Sure! I just assigned you to this issue.

And we're also running a hackathon right now named Modathon. We'd love for you to check it out 🙏🏻

https://nine-chronicles.dev/event/2024modathon

**Comment by umardevX** [comment]
Removing these unused items will help streamline the code and improve its readability. Could you please assign this task to me?

**Comment by umardevX** [comment]
@moreal Can you assign me on my this account again ?

**Comment by moreal** [comment]
@umardevX What is your relationship with @umar-source?

**Comment by umardevX** [comment]
@umar-source is my second account. and umardevX account is my new account.

**Comment by moreal** [comment]
Okay, I've changed assignee to @umardevX cc @umar-source
