### ISSUE TITLE
Replace `SetLegacyState(_, Null)` with `RemoveLegacyState(_)`

### ISSUE THREAD

**Issue by moreal** [planetarium/lib9c#2839]
## Motivation

Before Libplanet introduced the `IAccount` interface, there was no way to remove states. But since then, it is possible to remove states instead of setting them to `Null`.

## Work items

Replace `.SetLegacyState({address}, Null.Value)` with `.RemoveLegacyState({address})`

**Comment by TheMarvelFan** [comment]
Hi @moreal ,

I would like to contribute to this issue.

Thanks!

**Comment by moreal** [comment]
@TheMarvelFan I'm sorry for late reply and you can try this issue if you're still interested 🙏🏻 👍🏻
