### ISSUE TITLE
월드보스 보상 조정 (lib9c)

### ISSUE THREAD

**Issue by tyrosine1153** [planetarium/lib9c#2877]
- 보상 시트 구조 변경 ~~을 반영하기 위한 lib9c 변경~~
  - ~~static한 시트 구조 또한 아예 변경~~ Grade 보상은 스펙에서 삭제, 랭킹 보상만 수정
  - WorldBossRankingRewardSheet에 material 2개 추가

**Comment by ipdae** [comment]
- dp graphql type
- world boss service db migration
- world boss service action migration
