### ISSUE TITLE
Move `@planetarium` directory to under `integrations/javascript` directory

### ISSUE THREAD

**Issue by moreal** [planetarium/lib9c#2933]
## Overview

Please create a new directory `/integrations/javascript`, move `/@planetarium` to `/integrations/javascript/@planetarium` and update [publish.yaml#jsr](https://github.com/planetarium/lib9c/blob/8bea55389944c5b9a77eb68153db90e6a6793848/.github/workflows/publish.yml#L46-L51) GitHub Actions workflow step.

https://github.com/planetarium/lib9c/blob/8bea55389944c5b9a77eb68153db90e6a6793848/.github/workflows/publish.yml#L46-L51

Or, if another solution that you want to suggest, please let us know!

## Background

At the root of this repository is a directory called `@planetarium` because we referenced Libplanet's structure when creating our JavaScript library.

<img width="791" alt="Screenshot 2024-10-25 at 12 18 28 PM" src="https://github.com/user-attachments/assets/9d487279-7dbb-459a-8c92-e4281eaad353">

But I want lib9c to provide Python libraries as well. And I want these other language libraries to be stored together in one directory so that it's easy to distinguish them, so I propose to name the directory `integrations` and create subdirectories with lowercase language names (e.g., javascript, python, etc) to organise the workspace.

The end result should look something like this.

```
/integrations
  /javascript
    /@planetarium
  /python
```

**Comment by kanade012** [comment]
도전해보겠습니다
