### ISSUE TITLE
Setup Python library project

### ISSUE THREAD

**Issue by moreal** [planetarium/lib9c#2937]
## Overview

Set up a Python library project under `/integrations/python` directory.

I think a configuration with pyproject.toml according to [PEP-0621](https://peps.python.org/pep-0621/) would be good. Dependency Manager hasn't decided exactly which one to use, it looks like it needs some discussion, suggestions are welcome! All the author knows is rye and poetry.

## Background

In NineChronicles ecosystem, there are some services written in Python:

 - [planetarium/NineChronicles.IAP](https://github.com/planetarium/NineChronicles.IAP)
 - [planetarium/world-boss-service](https://github.com/planetarium/world-boss-service)

But they still create actions with GraphQL query or create actions with their own implementation:

- https://github.com/planetarium/NineChronicles.IAP/blob/98786545073190bf8a37dc51abafb6ba17862b47/common/lib9c/actions/claim_items.py
- https://github.com/planetarium/world-boss-service/blob/8524a2b8d83a1b87821252d3f7365091e658c55e/world_boss/app/raid.py#L303-L306

We and modders should make its own action implementation because there is no shared library to create action. (Like [lib9c.js](https://jsr.io/@planetarium/lib9c).

We need a Python library to avoid repeating that unnecessary process, and this issue is a first step towards that. 🚀

**Comment by forwardyoung** [comment]
제가 이 이슈 assign하겠습니다!
