### ISSUE TITLE
lib9c.js: implement `HackAndSlash`

### ISSUE THREAD

**Issue by Atralupus** [planetarium/lib9c#2943]
## Context

[`@planetarium/lib9c`][lib9c-jsr] provides JavaScript/TypeScript library which helps creating actions easily in JavaScript environment. But it doesn't implement [`HackAndSlash`][missing-action] yet. Please implement `HackAndSlash` action in `@planetarium/lib9c`.

[lib9c-jsr]: https://jsr.io/@planetarium/lib9c
[missing-action]: https://github.com/planetarium/lib9c/blob/39e8f48fd59f1ddbc05a035e5d1b5489ea0f18e4/Lib9c/Action/HackAndSlash.cs#L24

## Tips

Please read [`@planetarium/lib9c/CONTRIBUTING.md`](https://github.com/planetarium/lib9c/blob/development/%40planetarium/lib9c/CONTRIBUTING.md) to know how to make a new action and test it.

If you have any questions while resolving this issue, please ask in our Discord server. https://planetarium.dev/discord

**Comment by yeeSilver** [comment]
hacktoberfest start
