### ISSUE TITLE
Typo in `Nekoyume.Action.InitializeStates.Execute()`

### ISSUE THREAD

**Issue by moreal** [planetarium/lib9c#409]
There is a typo in `Nekoyume.Action.InitializeStates.Execute()`. It should be `pending` instead of `peding`.

https://github.com/planetarium/lib9c/blob/49050b6ccdfa387ab4c222ad674ffd56b289ce9a/Lib9c/Action/InitializeStates.cs#L146-L152

**Comment by krustev03** [comment]
Fixed.
