### ISSUE TITLE
Logging RewardGold execution time for block eval time.

### ISSUE THREAD

**Issue by ipdae** [planetarium/lib9c#916]
There is a case an empty tx with the eval time spike like this [block](https://9cscan.com/blocks/3762563).
Add step-by-step logging inside RewardGold like any other action to investigate this case.

**Comment by moreal** [comment]
Lib9c is logging `RewardGold` execution time at https://github.com/planetarium/lib9c/blob/4e12a6a657fe1eeccf7a7a1783b90ec70aab2cdd/Lib9c/Action/RewardGold.cs#L46
